// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

/*
Package v1 is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	ID
	Result
	Void
	NewUser
	ReadUser
	ReadUserLog
	UpdateUser
	NewGroup
	Group
	UpdateGroup
	GroupMember
	Members
	NewTransaction
	Transaction
	TID
*/
package v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ID struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *ID) Reset()                    { *m = ID{} }
func (m *ID) String() string            { return proto.CompactTextString(m) }
func (*ID) ProtoMessage()               {}
func (*ID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ID) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Result struct {
	Id     string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Status bool   `protobuf:"varint,2,opt,name=status" json:"status,omitempty"`
}

func (m *Result) Reset()                    { *m = Result{} }
func (m *Result) String() string            { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()               {}
func (*Result) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Result) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Result) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type Void struct {
}

func (m *Void) Reset()                    { *m = Void{} }
func (m *Void) String() string            { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()               {}
func (*Void) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// implement crud for user
// Create
type NewUser struct {
	FirstName string `protobuf:"bytes,1,opt,name=firstName" json:"firstName,omitempty"`
	LastName  string `protobuf:"bytes,2,opt,name=lastName" json:"lastName,omitempty"`
	Email     string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Password  string `protobuf:"bytes,4,opt,name=password" json:"password,omitempty"`
}

func (m *NewUser) Reset()                    { *m = NewUser{} }
func (m *NewUser) String() string            { return proto.CompactTextString(m) }
func (*NewUser) ProtoMessage()               {}
func (*NewUser) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *NewUser) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *NewUser) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *NewUser) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *NewUser) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// read
type ReadUser struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Email    string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
}

func (m *ReadUser) Reset()                    { *m = ReadUser{} }
func (m *ReadUser) String() string            { return proto.CompactTextString(m) }
func (*ReadUser) ProtoMessage()               {}
func (*ReadUser) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ReadUser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReadUser) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ReadUser) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type ReadUserLog struct {
	Transactions []*Transaction `protobuf:"bytes,5,rep,name=Transactions,json=transactions" json:"Transactions,omitempty"`
}

func (m *ReadUserLog) Reset()                    { *m = ReadUserLog{} }
func (m *ReadUserLog) String() string            { return proto.CompactTextString(m) }
func (*ReadUserLog) ProtoMessage()               {}
func (*ReadUserLog) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ReadUserLog) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

// update
type UpdateUser struct {
	Id        string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	FirstName string `protobuf:"bytes,2,opt,name=firstName" json:"firstName,omitempty"`
	LastName  string `protobuf:"bytes,3,opt,name=lastName" json:"lastName,omitempty"`
	Email     string `protobuf:"bytes,4,opt,name=email" json:"email,omitempty"`
	Familyid  string `protobuf:"bytes,5,opt,name=familyid" json:"familyid,omitempty"`
	Password  string `protobuf:"bytes,6,opt,name=password" json:"password,omitempty"`
}

func (m *UpdateUser) Reset()                    { *m = UpdateUser{} }
func (m *UpdateUser) String() string            { return proto.CompactTextString(m) }
func (*UpdateUser) ProtoMessage()               {}
func (*UpdateUser) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *UpdateUser) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateUser) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UpdateUser) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *UpdateUser) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UpdateUser) GetFamilyid() string {
	if m != nil {
		return m.Familyid
	}
	return ""
}

func (m *UpdateUser) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// implement crud for group
type NewGroup struct {
	Rate      float32 `protobuf:"fixed32,1,opt,name=rate" json:"rate,omitempty"`
	Name      string  `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Organiser string  `protobuf:"bytes,3,opt,name=organiser" json:"organiser,omitempty"`
}

func (m *NewGroup) Reset()                    { *m = NewGroup{} }
func (m *NewGroup) String() string            { return proto.CompactTextString(m) }
func (*NewGroup) ProtoMessage()               {}
func (*NewGroup) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *NewGroup) GetRate() float32 {
	if m != nil {
		return m.Rate
	}
	return 0
}

func (m *NewGroup) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NewGroup) GetOrganiser() string {
	if m != nil {
		return m.Organiser
	}
	return ""
}

// read
type Group struct {
	Id   string  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Rate float32 `protobuf:"fixed32,2,opt,name=rate" json:"rate,omitempty"`
	Name string  `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
}

func (m *Group) Reset()                    { *m = Group{} }
func (m *Group) String() string            { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()               {}
func (*Group) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Group) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Group) GetRate() float32 {
	if m != nil {
		return m.Rate
	}
	return 0
}

func (m *Group) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// update
type UpdateGroup struct {
	Id   string  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name string  `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Rate float32 `protobuf:"fixed32,3,opt,name=rate" json:"rate,omitempty"`
}

func (m *UpdateGroup) Reset()                    { *m = UpdateGroup{} }
func (m *UpdateGroup) String() string            { return proto.CompactTextString(m) }
func (*UpdateGroup) ProtoMessage()               {}
func (*UpdateGroup) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *UpdateGroup) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateGroup) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateGroup) GetRate() float32 {
	if m != nil {
		return m.Rate
	}
	return 0
}

type GroupMember struct {
	Id     string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Userid string `protobuf:"bytes,2,opt,name=userid" json:"userid,omitempty"`
}

func (m *GroupMember) Reset()                    { *m = GroupMember{} }
func (m *GroupMember) String() string            { return proto.CompactTextString(m) }
func (*GroupMember) ProtoMessage()               {}
func (*GroupMember) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *GroupMember) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GroupMember) GetUserid() string {
	if m != nil {
		return m.Userid
	}
	return ""
}

type Members struct {
	User []*ReadUser `protobuf:"bytes,1,rep,name=user" json:"user,omitempty"`
}

func (m *Members) Reset()                    { *m = Members{} }
func (m *Members) String() string            { return proto.CompactTextString(m) }
func (*Members) ProtoMessage()               {}
func (*Members) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *Members) GetUser() []*ReadUser {
	if m != nil {
		return m.User
	}
	return nil
}

type NewTransaction struct {
	Amount float32 `protobuf:"fixed32,1,opt,name=amount" json:"amount,omitempty"`
	Userid string  `protobuf:"bytes,2,opt,name=userid" json:"userid,omitempty"`
}

func (m *NewTransaction) Reset()                    { *m = NewTransaction{} }
func (m *NewTransaction) String() string            { return proto.CompactTextString(m) }
func (*NewTransaction) ProtoMessage()               {}
func (*NewTransaction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *NewTransaction) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *NewTransaction) GetUserid() string {
	if m != nil {
		return m.Userid
	}
	return ""
}

type Transaction struct {
	Id     string  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Amount float32 `protobuf:"fixed32,2,opt,name=amount" json:"amount,omitempty"`
	Userid string  `protobuf:"bytes,3,opt,name=userid" json:"userid,omitempty"`
}

func (m *Transaction) Reset()                    { *m = Transaction{} }
func (m *Transaction) String() string            { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()               {}
func (*Transaction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *Transaction) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Transaction) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Transaction) GetUserid() string {
	if m != nil {
		return m.Userid
	}
	return ""
}

type TID struct {
	Id     string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Userid string `protobuf:"bytes,2,opt,name=userid" json:"userid,omitempty"`
}

func (m *TID) Reset()                    { *m = TID{} }
func (m *TID) String() string            { return proto.CompactTextString(m) }
func (*TID) ProtoMessage()               {}
func (*TID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *TID) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TID) GetUserid() string {
	if m != nil {
		return m.Userid
	}
	return ""
}

func init() {
	proto.RegisterType((*ID)(nil), "v1.ID")
	proto.RegisterType((*Result)(nil), "v1.Result")
	proto.RegisterType((*Void)(nil), "v1.Void")
	proto.RegisterType((*NewUser)(nil), "v1.NewUser")
	proto.RegisterType((*ReadUser)(nil), "v1.ReadUser")
	proto.RegisterType((*ReadUserLog)(nil), "v1.ReadUserLog")
	proto.RegisterType((*UpdateUser)(nil), "v1.UpdateUser")
	proto.RegisterType((*NewGroup)(nil), "v1.NewGroup")
	proto.RegisterType((*Group)(nil), "v1.Group")
	proto.RegisterType((*UpdateGroup)(nil), "v1.UpdateGroup")
	proto.RegisterType((*GroupMember)(nil), "v1.GroupMember")
	proto.RegisterType((*Members)(nil), "v1.Members")
	proto.RegisterType((*NewTransaction)(nil), "v1.NewTransaction")
	proto.RegisterType((*Transaction)(nil), "v1.Transaction")
	proto.RegisterType((*TID)(nil), "v1.TID")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Users service

type UsersClient interface {
	// create new user
	Create(ctx context.Context, in *NewUser, opts ...grpc.CallOption) (*ID, error)
	// read user data
	Read(ctx context.Context, in *ID, opts ...grpc.CallOption) (*ReadUser, error)
	ReadLog(ctx context.Context, in *ID, opts ...grpc.CallOption) (*ReadUserLog, error)
	// update user data (logs included)
	Update(ctx context.Context, in *UpdateUser, opts ...grpc.CallOption) (*Result, error)
	// delete user
	Delete(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Result, error)
}

type usersClient struct {
	cc *grpc.ClientConn
}

func NewUsersClient(cc *grpc.ClientConn) UsersClient {
	return &usersClient{cc}
}

func (c *usersClient) Create(ctx context.Context, in *NewUser, opts ...grpc.CallOption) (*ID, error) {
	out := new(ID)
	err := grpc.Invoke(ctx, "/v1.Users/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) Read(ctx context.Context, in *ID, opts ...grpc.CallOption) (*ReadUser, error) {
	out := new(ReadUser)
	err := grpc.Invoke(ctx, "/v1.Users/Read", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) ReadLog(ctx context.Context, in *ID, opts ...grpc.CallOption) (*ReadUserLog, error) {
	out := new(ReadUserLog)
	err := grpc.Invoke(ctx, "/v1.Users/ReadLog", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) Update(ctx context.Context, in *UpdateUser, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := grpc.Invoke(ctx, "/v1.Users/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) Delete(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := grpc.Invoke(ctx, "/v1.Users/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Users service

type UsersServer interface {
	// create new user
	Create(context.Context, *NewUser) (*ID, error)
	// read user data
	Read(context.Context, *ID) (*ReadUser, error)
	ReadLog(context.Context, *ID) (*ReadUserLog, error)
	// update user data (logs included)
	Update(context.Context, *UpdateUser) (*Result, error)
	// delete user
	Delete(context.Context, *ID) (*Result, error)
}

func RegisterUsersServer(s *grpc.Server, srv UsersServer) {
	s.RegisterService(&_Users_serviceDesc, srv)
}

func _Users_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Users/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).Create(ctx, req.(*NewUser))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Users/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).Read(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_ReadLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).ReadLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Users/ReadLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).ReadLog(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Users/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).Update(ctx, req.(*UpdateUser))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Users/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).Delete(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

var _Users_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.Users",
	HandlerType: (*UsersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Users_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Users_Read_Handler,
		},
		{
			MethodName: "ReadLog",
			Handler:    _Users_ReadLog_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Users_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Users_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

// Client API for Groups service

type GroupsClient interface {
	Create(ctx context.Context, in *NewGroup, opts ...grpc.CallOption) (*ID, error)
	Read(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Group, error)
	ReadGroupMembers(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Members, error)
	ReadGroupOrganiser(ctx context.Context, in *ID, opts ...grpc.CallOption) (*ReadUser, error)
	Update(ctx context.Context, in *UpdateGroup, opts ...grpc.CallOption) (*Result, error)
	UpdateMember(ctx context.Context, in *GroupMember, opts ...grpc.CallOption) (*Result, error)
	Delete(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Result, error)
	DeleteMember(ctx context.Context, in *GroupMember, opts ...grpc.CallOption) (*Result, error)
}

type groupsClient struct {
	cc *grpc.ClientConn
}

func NewGroupsClient(cc *grpc.ClientConn) GroupsClient {
	return &groupsClient{cc}
}

func (c *groupsClient) Create(ctx context.Context, in *NewGroup, opts ...grpc.CallOption) (*ID, error) {
	out := new(ID)
	err := grpc.Invoke(ctx, "/v1.Groups/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupsClient) Read(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Group, error) {
	out := new(Group)
	err := grpc.Invoke(ctx, "/v1.Groups/Read", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupsClient) ReadGroupMembers(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Members, error) {
	out := new(Members)
	err := grpc.Invoke(ctx, "/v1.Groups/ReadGroupMembers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupsClient) ReadGroupOrganiser(ctx context.Context, in *ID, opts ...grpc.CallOption) (*ReadUser, error) {
	out := new(ReadUser)
	err := grpc.Invoke(ctx, "/v1.Groups/ReadGroupOrganiser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupsClient) Update(ctx context.Context, in *UpdateGroup, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := grpc.Invoke(ctx, "/v1.Groups/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupsClient) UpdateMember(ctx context.Context, in *GroupMember, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := grpc.Invoke(ctx, "/v1.Groups/UpdateMember", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupsClient) Delete(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := grpc.Invoke(ctx, "/v1.Groups/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupsClient) DeleteMember(ctx context.Context, in *GroupMember, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := grpc.Invoke(ctx, "/v1.Groups/DeleteMember", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Groups service

type GroupsServer interface {
	Create(context.Context, *NewGroup) (*ID, error)
	Read(context.Context, *ID) (*Group, error)
	ReadGroupMembers(context.Context, *ID) (*Members, error)
	ReadGroupOrganiser(context.Context, *ID) (*ReadUser, error)
	Update(context.Context, *UpdateGroup) (*Result, error)
	UpdateMember(context.Context, *GroupMember) (*Result, error)
	Delete(context.Context, *ID) (*Result, error)
	DeleteMember(context.Context, *GroupMember) (*Result, error)
}

func RegisterGroupsServer(s *grpc.Server, srv GroupsServer) {
	s.RegisterService(&_Groups_serviceDesc, srv)
}

func _Groups_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewGroup)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Groups/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupsServer).Create(ctx, req.(*NewGroup))
	}
	return interceptor(ctx, in, info, handler)
}

func _Groups_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupsServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Groups/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupsServer).Read(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Groups_ReadGroupMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupsServer).ReadGroupMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Groups/ReadGroupMembers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupsServer).ReadGroupMembers(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Groups_ReadGroupOrganiser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupsServer).ReadGroupOrganiser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Groups/ReadGroupOrganiser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupsServer).ReadGroupOrganiser(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Groups_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGroup)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupsServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Groups/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupsServer).Update(ctx, req.(*UpdateGroup))
	}
	return interceptor(ctx, in, info, handler)
}

func _Groups_UpdateMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupMember)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupsServer).UpdateMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Groups/UpdateMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupsServer).UpdateMember(ctx, req.(*GroupMember))
	}
	return interceptor(ctx, in, info, handler)
}

func _Groups_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupsServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Groups/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupsServer).Delete(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Groups_DeleteMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupMember)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupsServer).DeleteMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Groups/DeleteMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupsServer).DeleteMember(ctx, req.(*GroupMember))
	}
	return interceptor(ctx, in, info, handler)
}

var _Groups_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.Groups",
	HandlerType: (*GroupsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Groups_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Groups_Read_Handler,
		},
		{
			MethodName: "ReadGroupMembers",
			Handler:    _Groups_ReadGroupMembers_Handler,
		},
		{
			MethodName: "ReadGroupOrganiser",
			Handler:    _Groups_ReadGroupOrganiser_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Groups_Update_Handler,
		},
		{
			MethodName: "UpdateMember",
			Handler:    _Groups_UpdateMember_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Groups_Delete_Handler,
		},
		{
			MethodName: "DeleteMember",
			Handler:    _Groups_DeleteMember_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

// Client API for Transactions service

type TransactionsClient interface {
	Create(ctx context.Context, in *NewTransaction, opts ...grpc.CallOption) (*Result, error)
	ReadTransaction(ctx context.Context, in *TID, opts ...grpc.CallOption) (*Transaction, error)
}

type transactionsClient struct {
	cc *grpc.ClientConn
}

func NewTransactionsClient(cc *grpc.ClientConn) TransactionsClient {
	return &transactionsClient{cc}
}

func (c *transactionsClient) Create(ctx context.Context, in *NewTransaction, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := grpc.Invoke(ctx, "/v1.Transactions/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionsClient) ReadTransaction(ctx context.Context, in *TID, opts ...grpc.CallOption) (*Transaction, error) {
	out := new(Transaction)
	err := grpc.Invoke(ctx, "/v1.Transactions/ReadTransaction", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Transactions service

type TransactionsServer interface {
	Create(context.Context, *NewTransaction) (*Result, error)
	ReadTransaction(context.Context, *TID) (*Transaction, error)
}

func RegisterTransactionsServer(s *grpc.Server, srv TransactionsServer) {
	s.RegisterService(&_Transactions_serviceDesc, srv)
}

func _Transactions_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewTransaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Transactions/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionsServer).Create(ctx, req.(*NewTransaction))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transactions_ReadTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionsServer).ReadTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Transactions/ReadTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionsServer).ReadTransaction(ctx, req.(*TID))
	}
	return interceptor(ctx, in, info, handler)
}

var _Transactions_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.Transactions",
	HandlerType: (*TransactionsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Transactions_Create_Handler,
		},
		{
			MethodName: "ReadTransaction",
			Handler:    _Transactions_ReadTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 635 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xdd, 0x6e, 0xd3, 0x4c,
	0x10, 0xb5, 0xd7, 0x8e, 0xd3, 0x8c, 0xa3, 0xe6, 0xd3, 0xaa, 0xaa, 0xac, 0x7c, 0x15, 0x44, 0x2b,
	0x04, 0xe5, 0xa7, 0x15, 0x4d, 0xc5, 0x35, 0x08, 0x8a, 0x50, 0xa5, 0x36, 0x20, 0xab, 0xe5, 0x7e,
	0x8b, 0xb7, 0xd1, 0x4a, 0x89, 0x1d, 0x79, 0xed, 0x46, 0xbc, 0x0f, 0xcf, 0xc0, 0x2b, 0xf0, 0x5a,
	0x68, 0x7f, 0x6c, 0xaf, 0x93, 0x18, 0xc1, 0x55, 0x3c, 0x73, 0x66, 0xcf, 0xcc, 0x9c, 0x99, 0xdd,
	0xc0, 0x80, 0xae, 0xf8, 0xe9, 0x2a, 0xcf, 0x8a, 0x0c, 0xa3, 0x87, 0x33, 0x72, 0x00, 0xe8, 0xf2,
	0x02, 0xef, 0x03, 0xe2, 0x49, 0xe4, 0x4e, 0xdc, 0xe3, 0x41, 0x8c, 0x78, 0x42, 0x5e, 0x43, 0x10,
	0x33, 0x51, 0x2e, 0x8a, 0x4d, 0x04, 0x1f, 0x42, 0x20, 0x0a, 0x5a, 0x94, 0x22, 0x42, 0x13, 0xf7,
	0x78, 0x2f, 0x36, 0x16, 0x09, 0xc0, 0xff, 0x9a, 0xf1, 0x84, 0x94, 0xd0, 0x9f, 0xb1, 0xf5, 0xad,
	0x60, 0x39, 0x3e, 0x82, 0xc1, 0x3d, 0xcf, 0x45, 0x31, 0xa3, 0x4b, 0x66, 0x18, 0x1a, 0x07, 0x1e,
	0xc3, 0xde, 0x82, 0x1a, 0x10, 0x29, 0xb0, 0xb6, 0xf1, 0x01, 0xf4, 0xd8, 0x92, 0xf2, 0x45, 0xe4,
	0x29, 0x40, 0x1b, 0xf2, 0xc4, 0x8a, 0x0a, 0xb1, 0xce, 0xf2, 0x24, 0xf2, 0xf5, 0x89, 0xca, 0x26,
	0x5f, 0x60, 0x2f, 0x66, 0x34, 0x51, 0x79, 0x31, 0xf8, 0x69, 0x93, 0x52, 0x7d, 0xcb, 0xb3, 0xa5,
	0x60, 0x79, 0x6a, 0x65, 0xab, 0xec, 0xdd, 0xd9, 0xc8, 0x7b, 0x08, 0x2b, 0xc6, 0xab, 0x6c, 0x8e,
	0xcf, 0x61, 0x78, 0x93, 0xd3, 0x54, 0xd0, 0x6f, 0x05, 0xcf, 0x52, 0x11, 0xf5, 0x26, 0xde, 0x71,
	0x38, 0x1d, 0x9d, 0x3e, 0x9c, 0x9d, 0x5a, 0xfe, 0x78, 0x58, 0x58, 0x41, 0xe4, 0x87, 0x0b, 0x70,
	0xbb, 0x4a, 0x68, 0xc1, 0x54, 0x61, 0x9b, 0x5a, 0xb6, 0x04, 0x42, 0x7f, 0x12, 0xc8, 0xeb, 0x12,
	0xc8, 0xdf, 0x10, 0xe8, 0x9e, 0x2e, 0xf9, 0xe2, 0x3b, 0x4f, 0xa2, 0x9e, 0x3e, 0x51, 0xd9, 0x2d,
	0xf1, 0x82, 0x6d, 0xf1, 0x66, 0x6c, 0xfd, 0x29, 0xcf, 0xca, 0x95, 0x14, 0x2f, 0xa7, 0x85, 0x16,
	0x0f, 0xc5, 0xea, 0xbb, 0x16, 0x14, 0x59, 0x82, 0x1e, 0xc1, 0x20, 0xcb, 0xe7, 0x34, 0xe5, 0x82,
	0xe5, 0xa6, 0xbc, 0xc6, 0x41, 0xde, 0x42, 0x4f, 0xd3, 0x6d, 0xb6, 0x5c, 0xd1, 0xa3, 0x1d, 0xf4,
	0x5e, 0x43, 0x4f, 0x3e, 0x42, 0xa8, 0x85, 0xeb, 0xa4, 0xd9, 0xaa, 0xa8, 0xa2, 0xf6, 0x1a, 0x6a,
	0xf2, 0x06, 0x42, 0x45, 0x70, 0xcd, 0x96, 0x77, 0x3b, 0x06, 0x70, 0x08, 0x81, 0xdc, 0x02, 0x9e,
	0x18, 0x22, 0x63, 0x91, 0x97, 0xd0, 0xd7, 0x27, 0x04, 0x9e, 0x80, 0x2f, 0x9d, 0x91, 0xab, 0xe6,
	0x3d, 0x94, 0xf3, 0xae, 0xd6, 0x22, 0x56, 0x08, 0x79, 0x07, 0xfb, 0x33, 0xb6, 0xb6, 0x96, 0x40,
	0xd2, 0xd2, 0x65, 0x56, 0xa6, 0x85, 0x51, 0xd1, 0x58, 0x9d, 0xe9, 0xae, 0x21, 0xb4, 0x8f, 0xef,
	0xa8, 0xd2, 0xd0, 0xa1, 0x0e, 0x3a, 0xaf, 0x45, 0x77, 0x02, 0xde, 0xcd, 0xf6, 0x9d, 0xee, 0xca,
	0x3e, 0xfd, 0xe9, 0x42, 0x4f, 0xb6, 0x23, 0xf0, 0x63, 0x08, 0x3e, 0xe4, 0x4c, 0x8e, 0x24, 0x94,
	0x7d, 0x9a, 0x7b, 0x3c, 0x0e, 0xa4, 0x71, 0x79, 0x41, 0x1c, 0xfc, 0x08, 0x7c, 0xd9, 0x3c, 0x36,
	0x9e, 0x71, 0x4b, 0x0e, 0xe2, 0xe0, 0x27, 0xd0, 0x97, 0x96, 0xbc, 0x2f, 0x55, 0xc8, 0xc8, 0x0e,
	0xb9, 0xca, 0xe6, 0xc4, 0xc1, 0x4f, 0x21, 0xd0, 0xb3, 0xc5, 0xfb, 0x12, 0x6c, 0x2e, 0xc8, 0x18,
	0x74, 0xb0, 0x7c, 0x78, 0x54, 0xb6, 0xe0, 0x82, 0x2d, 0x58, 0xc1, 0x6a, 0xb2, 0x16, 0x3e, 0xfd,
	0x85, 0x20, 0x50, 0xd3, 0x95, 0x53, 0xaa, 0x2a, 0x1f, 0x9a, 0xca, 0x15, 0x60, 0x95, 0xfe, 0xff,
	0x46, 0xe9, 0x03, 0xf9, 0xab, 0x82, 0x88, 0x83, 0x9f, 0xc3, 0x7f, 0x12, 0xb4, 0x56, 0x45, 0xd4,
	0x81, 0x4a, 0x0a, 0xe3, 0x24, 0x0e, 0x7e, 0x05, 0xb8, 0x0e, 0xfd, 0x5c, 0xed, 0x7b, 0xa7, 0x20,
	0xcf, 0xea, 0x56, 0x47, 0x4d, 0xab, 0xba, 0xb4, 0x76, 0xaf, 0x27, 0x30, 0xd4, 0xa0, 0xd9, 0xd4,
	0x51, 0x5d, 0x9e, 0x76, 0xfc, 0x9b, 0x34, 0x92, 0x4e, 0xe3, 0x7f, 0x45, 0x37, 0xe5, 0xed, 0xc7,
	0x0d, 0xbf, 0xa8, 0xe5, 0xc4, 0x46, 0x4e, 0x0b, 0xde, 0x4a, 0x35, 0x92, 0x0d, 0xdb, 0x0b, 0xdc,
	0x57, 0xaf, 0x62, 0x35, 0x7c, 0x0b, 0x21, 0xce, 0x5d, 0xa0, 0xfe, 0x7a, 0xce, 0x7f, 0x07, 0x00,
	0x00, 0xff, 0xff, 0x7e, 0xe7, 0xd0, 0xc9, 0x87, 0x06, 0x00, 0x00,
}
